micronaut:
  server:
    cors:
      enabled: true
  application:
    name: desafioWarriors

endpoints:
  health:
    enabled: true

cassandra:
  default:
    basic:
      contact-points:
        - "172.19.0.4:9042"
        - "172.19.0.3:9042"
        - "172.19.0.2:9042"
      session-keyspace: ${scylladb_session_keyspace:product}
      load-balancing-policy:
        local-datacenter: ${scylladb_local_datacenter:datacenter1}